# Spring Boot configuration
spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: mysecretpassword
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # when launching the application for the first time - switch "update" at "create" or "create-drop"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  # Email Settings
  mail:
    host: localhost # email-smtp.us-west-2.amazonaws.com
    port: 1025 # 25
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080
#  servlet:
#    context-path: /user-management