# Spring Boot configuration
spring:
  profiles:
    active: development
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: mysecretpassword
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # when launching the application for the first time - switch "update" at "create" or "create-drop"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      client:
        registration:
          # get from https://console.cloud.google.com/apis/credentials
          google:
            clientId: 
            clientSecret: 
            scope:
              - email
              - profile
app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080
  error:
    include-message: always
    include-exception: false
#  servlet:
#    context-path: /user-management
